description:        "sddfgs&#x0D;&#x000A;adfa"

name:               "hejw005"


url:                ""
author:             "hejw005"
email:              "hejingwuuestc@163.com"
gravatar_hash:      "205e460b479e2e5b48aec07710c08d50"
twitter:            "jhondoe"
email:              "hejingwuuestc@163.com"
github:             "jhondoe"
pinterest:          "jhondoe"
linkedin:           "jhondoe"
facebook:           "jhondoe"

disqus_shortname:   "thinker"

background:         "http://on7h80zkk.bkt.clouddn.com/timg.jpeg"

paginate:           5
paginate_path:      "/page:num/"

baseurl:            ""
permalink:          /:year/:month/:day/:title/

markdown:           kramdown

nav:
  - name:           "About"
    href:           "/about"
  - name:           "Download"
    href:           "/releases"

sass:
  style:            :compressed

defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

gems:
  - jekyll-paginate
  
show_drafts: BOOL
